name: CI

on:
  push:
    branches-ignore: [ with-actions ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn set version stable
          yarn install --immutable

      - name: Type check
        run: yarn type-check

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Tests
        run: yarn test
